### ISSUE TITLE
Prefixing variables

### ISSUE THREAD

**Issue by kylemac** [carrot/grate#1]
> note: this is a repost of @leepowellcouk issue comment - https://github.com/mojotech/jeet/issues/123#issuecomment-32470743 . apologies for not having issues enabled. 

Just an idea - for Grate, is it worth prefixing the settings variables? Just to avoid any potential conflicts with other plugins?

```
grate-gutter = 3
grate-parent-first = false
grate-layout-direction = LTR
```

I've noticed when mashing a few stylus libraries together that occasionally you encounter conflicts around global variables.

edit: variables using underscores

**Comment by leepowelldev** [comment]
Thanks. Sorry, they should be using underscores...

**Comment by jescalan** [comment]
yeah this is a good call. Anyone wanna pull request this one?

**Comment by leepowelldev** [comment]
Sure I can do that.

**Comment by kylemac** [comment]
@leepowellcouk hey sorry, I jumped on this quickly. should have dropped that in the ticket beforehand

**Comment by leepowelldev** [comment]
No worries.

**Comment by jescalan** [comment]
Thanks guys :+1:

**Comment by kylemac** [comment]
yeah great input @leepowellcouk - thanks for contributing!
