### ISSUE TITLE
improve README

### ISSUE THREAD

**Issue by kylemac** [carrot/grate#3]
we should probably include some documentation about the grate settings as well as moving the stylus plugin info directly into the readme

**Comment by jescalan** [comment]
I agree, the docs and settings info should definitely be a priority. As for the usage of stylus plugins, I'd rather keep that out of the direct readme just because we maintain a number of stylus plugins and it's much better to keep that info in one place rather than in multiple.

**Comment by kylemac** [comment]
@jenius I agree with that

**Comment by jescalan** [comment]
Done in 50de137f47d90d7d541dd66e2ac79e4edd225c5d
